//authors: Gavin Gray, Dan Ruley, and Windows Forms Sept/Oct 2019
using System.Windows.Forms;

namespace SpreadsheetGUI
{
    /// <summary>
    /// Handles disposal of the SpreadsheetForm and also contains autogenerated code from Windows Forms.
    /// </summary>
    partial class SpreadsheetForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;


        /// <summary>
        /// Prompts the user if they are about to close a spreadsheet with unsaved changes.
        /// </summary>
        /// 
        /// <returns>true for "yes"; false for "no"</returns>
        private bool UnsavedPrompt()
        {
                string message = "There are unsaved changes in this spreadsheet.  Proceed without saving?";
                string caption = "Warning";
                MessageBoxButtons buttons = MessageBoxButtons.YesNo;
                DialogResult result;
                result = MessageBox.Show(message, caption, buttons);
            if (result == System.Windows.Forms.DialogResult.Yes)
                return true;
            else
                return false;
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (form_spreadsheet.Changed)
            {
                bool close = UnsavedPrompt();

                //User selected "No" - do not close the window so they can save.
                if (!close)
                    return;
            }
            
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SpreadsheetForm));
            this.SpreadsheetGrid = new SS.SpreadsheetPanel();
            this.CoordDisplayBox = new System.Windows.Forms.TextBox();
            this.DisplayValueBox = new System.Windows.Forms.TextBox();
            this.DisplayContentsBox = new System.Windows.Forms.TextBox();
            this.SetContentsButton = new System.Windows.Forms.Button();
            this.MenuStrip = new System.Windows.Forms.MenuStrip();
            this.FileMenuHeader = new System.Windows.Forms.ToolStripMenuItem();
            this.NewMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.OpenFileMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.openImageToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ChatWithDannyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.OpenNewImageToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.SaveToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.SaveAsFileMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.CloseMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.HelpMenuHeader = new System.Windows.Forms.ToolStripMenuItem();
            this.HowToUseThisSpreadsheetToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.KeyboardShortcutsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.OpenFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.SaveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.ErrorNotify = new System.Windows.Forms.ErrorProvider(this.components);
            this.ErrorTimer = new System.Windows.Forms.Timer(this.components);
            this.ErrorText = new System.Windows.Forms.TextBox();
            this.MenuStrip.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ErrorNotify)).BeginInit();
            this.SuspendLayout();
            // 
            // SpreadsheetGrid
            // 
            this.SpreadsheetGrid.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.SpreadsheetGrid.Font = new System.Drawing.Font("Consolas", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SpreadsheetGrid.Location = new System.Drawing.Point(0, 75);
            this.SpreadsheetGrid.Margin = new System.Windows.Forms.Padding(4);
            this.SpreadsheetGrid.Name = "SpreadsheetGrid";
            this.SpreadsheetGrid.Size = new System.Drawing.Size(808, 383);
            this.SpreadsheetGrid.TabIndex = 0;
            // 
            // CoordDisplayBox
            // 
            this.CoordDisplayBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.CoordDisplayBox.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.CoordDisplayBox.Enabled = false;
            this.CoordDisplayBox.Font = new System.Drawing.Font("Consolas", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CoordDisplayBox.Location = new System.Drawing.Point(12, 31);
            this.CoordDisplayBox.MaxLength = 3;
            this.CoordDisplayBox.Name = "CoordDisplayBox";
            this.CoordDisplayBox.ReadOnly = true;
            this.CoordDisplayBox.Size = new System.Drawing.Size(63, 29);
            this.CoordDisplayBox.TabIndex = 1;
            this.CoordDisplayBox.TabStop = false;
            this.CoordDisplayBox.TextChanged += new System.EventHandler(this.CoordDisplayBox_TextChanged);
            // 
            // DisplayValueBox
            // 
            this.DisplayValueBox.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.DisplayValueBox.Enabled = false;
            this.DisplayValueBox.Font = new System.Drawing.Font("Consolas", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DisplayValueBox.Location = new System.Drawing.Point(81, 28);
            this.DisplayValueBox.Name = "DisplayValueBox";
            this.DisplayValueBox.ReadOnly = true;
            this.DisplayValueBox.Size = new System.Drawing.Size(247, 36);
            this.DisplayValueBox.TabIndex = 2;
            this.DisplayValueBox.TabStop = false;
            // 
            // DisplayContentsBox
            // 
            this.DisplayContentsBox.Font = new System.Drawing.Font("Consolas", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DisplayContentsBox.Location = new System.Drawing.Point(349, 28);
            this.DisplayContentsBox.Name = "DisplayContentsBox";
            this.DisplayContentsBox.Size = new System.Drawing.Size(247, 36);
            this.DisplayContentsBox.TabIndex = 3;
            // 
            // SetContentsButton
            // 
            this.SetContentsButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.SetContentsButton.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.SetContentsButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.SetContentsButton.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.SetContentsButton.Font = new System.Drawing.Font("Consolas", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SetContentsButton.Location = new System.Drawing.Point(632, 28);
            this.SetContentsButton.Name = "SetContentsButton";
            this.SetContentsButton.Size = new System.Drawing.Size(132, 35);
            this.SetContentsButton.TabIndex = 4;
            this.SetContentsButton.Text = "Set";
            this.SetContentsButton.UseVisualStyleBackColor = true;
            // 
            // MenuStrip
            // 
            this.MenuStrip.ImageScalingSize = new System.Drawing.Size(24, 24);
            this.MenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.FileMenuHeader,
            this.HelpMenuHeader});
            this.MenuStrip.Location = new System.Drawing.Point(0, 0);
            this.MenuStrip.Name = "MenuStrip";
            this.MenuStrip.Padding = new System.Windows.Forms.Padding(4, 1, 0, 1);
            this.MenuStrip.Size = new System.Drawing.Size(810, 24);
            this.MenuStrip.TabIndex = 5;
            this.MenuStrip.Text = "File";
            // 
            // FileMenuHeader
            // 
            this.FileMenuHeader.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.NewMenuItem,
            this.OpenFileMenuItem,
            this.openImageToolStripMenuItem,
            this.SaveToolStripMenuItem,
            this.SaveAsFileMenuItem,
            this.CloseMenuItem});
            this.FileMenuHeader.Name = "FileMenuHeader";
            this.FileMenuHeader.Size = new System.Drawing.Size(37, 22);
            this.FileMenuHeader.Text = "File";
            // 
            // NewMenuItem
            // 
            this.NewMenuItem.Name = "NewMenuItem";
            this.NewMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
            this.NewMenuItem.Size = new System.Drawing.Size(186, 22);
            this.NewMenuItem.Text = "New";
            this.NewMenuItem.Click += new System.EventHandler(this.NewMenuItem_Click);
            // 
            // OpenFileMenuItem
            // 
            this.OpenFileMenuItem.Name = "OpenFileMenuItem";
            this.OpenFileMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O)));
            this.OpenFileMenuItem.Size = new System.Drawing.Size(186, 22);
            this.OpenFileMenuItem.Text = "Open File";
            this.OpenFileMenuItem.Click += new System.EventHandler(this.OpenFileToolStripMenuItem_Click);
            // 
            // openImageToolStripMenuItem
            // 
            this.openImageToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ChatWithDannyToolStripMenuItem,
            this.OpenNewImageToolStripMenuItem});
            this.openImageToolStripMenuItem.Name = "openImageToolStripMenuItem";
            this.openImageToolStripMenuItem.Size = new System.Drawing.Size(186, 22);
            this.openImageToolStripMenuItem.Text = "Open Image";
            // 
            // ChatWithDannyToolStripMenuItem
            // 
            this.ChatWithDannyToolStripMenuItem.Name = "ChatWithDannyToolStripMenuItem";
            this.ChatWithDannyToolStripMenuItem.Size = new System.Drawing.Size(166, 22);
            this.ChatWithDannyToolStripMenuItem.Text = "Chat With Danny";
            this.ChatWithDannyToolStripMenuItem.Click += new System.EventHandler(this.chatWithDannyToolStripMenuItem_Click);
            // 
            // OpenNewImageToolStripMenuItem
            // 
            this.OpenNewImageToolStripMenuItem.Name = "OpenNewImageToolStripMenuItem";
            this.OpenNewImageToolStripMenuItem.Size = new System.Drawing.Size(166, 22);
            this.OpenNewImageToolStripMenuItem.Text = "Open New Image";
            this.OpenNewImageToolStripMenuItem.Click += new System.EventHandler(this.openNewImageToolStripMenuItem_Click);
            // 
            // SaveToolStripMenuItem
            // 
            this.SaveToolStripMenuItem.Name = "SaveToolStripMenuItem";
            this.SaveToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S)));
            this.SaveToolStripMenuItem.Size = new System.Drawing.Size(186, 22);
            this.SaveToolStripMenuItem.Text = "Save";
            this.SaveToolStripMenuItem.Click += new System.EventHandler(this.saveToolStripMenuItem_Click);
            // 
            // SaveAsFileMenuItem
            // 
            this.SaveAsFileMenuItem.Name = "SaveAsFileMenuItem";
            this.SaveAsFileMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
            | System.Windows.Forms.Keys.S)));
            this.SaveAsFileMenuItem.Size = new System.Drawing.Size(186, 22);
            this.SaveAsFileMenuItem.Text = "Save As";
            this.SaveAsFileMenuItem.Click += new System.EventHandler(this.SaveFileToolStripMenuItem_Click);
            // 
            // CloseMenuItem
            // 
            this.CloseMenuItem.Name = "CloseMenuItem";
            this.CloseMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)(((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Shift) 
            | System.Windows.Forms.Keys.C)));
            this.CloseMenuItem.Size = new System.Drawing.Size(186, 22);
            this.CloseMenuItem.Text = "Close";
            this.CloseMenuItem.Click += new System.EventHandler(this.CloseMenuItem_Click);
            // 
            // HelpMenuHeader
            // 
            this.HelpMenuHeader.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.HowToUseThisSpreadsheetToolStripMenuItem,
            this.KeyboardShortcutsToolStripMenuItem});
            this.HelpMenuHeader.Name = "HelpMenuHeader";
            this.HelpMenuHeader.Size = new System.Drawing.Size(44, 22);
            this.HelpMenuHeader.Text = "Help";
            // 
            // HowToUseThisSpreadsheetToolStripMenuItem
            // 
            this.HowToUseThisSpreadsheetToolStripMenuItem.Name = "HowToUseThisSpreadsheetToolStripMenuItem";
            this.HowToUseThisSpreadsheetToolStripMenuItem.Size = new System.Drawing.Size(226, 22);
            this.HowToUseThisSpreadsheetToolStripMenuItem.Text = "How to Use This Spreadsheet";
            this.HowToUseThisSpreadsheetToolStripMenuItem.Click += new System.EventHandler(this.howToUseThisSpreadsheetToolStripMenuItem_Click);
            // 
            // KeyboardShortcutsToolStripMenuItem
            // 
            this.KeyboardShortcutsToolStripMenuItem.Name = "KeyboardShortcutsToolStripMenuItem";
            this.KeyboardShortcutsToolStripMenuItem.Size = new System.Drawing.Size(226, 22);
            this.KeyboardShortcutsToolStripMenuItem.Text = "Keyboard Shortcuts";
            this.KeyboardShortcutsToolStripMenuItem.Click += new System.EventHandler(this.KeyboardShortcutsToolStripMenuItem_Click);
            // 
            // OpenFileDialog
            // 
            this.OpenFileDialog.FileName = "openFileDialog1";
            this.OpenFileDialog.FileOk += new System.ComponentModel.CancelEventHandler(this.OpenFileDialog_FileOk);
            // 
            // ErrorNotify
            // 
            this.ErrorNotify.BlinkRate = 0;
            this.ErrorNotify.BlinkStyle = System.Windows.Forms.ErrorBlinkStyle.NeverBlink;
            this.ErrorNotify.ContainerControl = this;
            this.ErrorNotify.Icon = ((System.Drawing.Icon)(resources.GetObject("ErrorNotify.Icon")));
            // 
            // ErrorTimer
            // 
            this.ErrorTimer.Interval = 5000;
            // 
            // ErrorText
            // 
            this.ErrorText.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.ErrorText.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.ErrorText.Enabled = false;
            this.ErrorText.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ErrorText.ForeColor = System.Drawing.SystemColors.MenuText;
            this.ErrorText.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.ErrorText.Location = new System.Drawing.Point(364, 8);
            this.ErrorText.MaxLength = 50;
            this.ErrorText.Name = "ErrorText";
            this.ErrorText.ReadOnly = true;
            this.ErrorText.Size = new System.Drawing.Size(209, 14);
            this.ErrorText.TabIndex = 6;
            this.ErrorText.TabStop = false;
            // 
            // SpreadsheetForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(810, 457);
            this.Controls.Add(this.ErrorText);
            this.Controls.Add(this.SetContentsButton);
            this.Controls.Add(this.DisplayContentsBox);
            this.Controls.Add(this.DisplayValueBox);
            this.Controls.Add(this.CoordDisplayBox);
            this.Controls.Add(this.SpreadsheetGrid);
            this.Controls.Add(this.MenuStrip);
            this.HelpButton = true;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.MainMenuStrip = this.MenuStrip;
            this.Name = "SpreadsheetForm";
            this.MenuStrip.ResumeLayout(false);
            this.MenuStrip.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ErrorNotify)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private SS.SpreadsheetPanel SpreadsheetGrid;
        private System.Windows.Forms.TextBox CoordDisplayBox;
        private System.Windows.Forms.TextBox DisplayValueBox;
        private System.Windows.Forms.TextBox DisplayContentsBox;
        private System.Windows.Forms.Button SetContentsButton;


        private System.Windows.Forms.MenuStrip MenuStrip;
        private System.Windows.Forms.ToolStripMenuItem FileMenuHeader;
        private System.Windows.Forms.ToolStripMenuItem OpenFileMenuItem;
        private System.Windows.Forms.ToolStripMenuItem SaveAsFileMenuItem;
        private System.Windows.Forms.ToolStripMenuItem NewMenuItem;
        private System.Windows.Forms.OpenFileDialog OpenFileDialog;
        private System.Windows.Forms.SaveFileDialog SaveFileDialog;
        private System.Windows.Forms.ToolStripMenuItem HelpMenuHeader;
        private System.Windows.Forms.ToolStripMenuItem CloseMenuItem;
        private System.Windows.Forms.ErrorProvider ErrorNotify;
        private Timer ErrorTimer;
        private ToolStripMenuItem KeyboardShortcutsToolStripMenuItem;
        private TextBox ErrorText;
        private ToolStripMenuItem SaveToolStripMenuItem;
        private ToolStripMenuItem HowToUseThisSpreadsheetToolStripMenuItem;
        private ToolStripMenuItem openImageToolStripMenuItem;
        private ToolStripMenuItem ChatWithDannyToolStripMenuItem;
        private ToolStripMenuItem OpenNewImageToolStripMenuItem;
    }
}

